// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8IZJDutKVNkJE2GJP1I_Zv0fSe8ZCmbI',
    appId: '1:745486986028:web:0ff39e698eb07575431a89',
    messagingSenderId: '745486986028',
    projectId: 'macrofit-d0635',
    authDomain: 'macrofit-d0635.firebaseapp.com',
    storageBucket: 'macrofit-d0635.firebasestorage.app',
    measurementId: 'G-WGMLMECVFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLBvPg0VgM3MBVktZG66pFxsRoTZSWck',
    appId: '1:745486986028:android:9dbb750dfc247f6a431a89',
    messagingSenderId: '745486986028',
    projectId: 'macrofit-d0635',
    storageBucket: 'macrofit-d0635.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3MKRFA0sriUqG9PbR8RVNGgGp9NoTYRs',
    appId: '1:745486986028:ios:7ef23969dde387a7431a89',
    messagingSenderId: '745486986028',
    projectId: 'macrofit-d0635',
    storageBucket: 'macrofit-d0635.firebasestorage.app',
    iosClientId: '745486986028-3652n9k6k944798j4vov39uk1mlaiqcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.macrofit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8IZJDutKVNkJE2GJP1I_Zv0fSe8ZCmbI',
    appId: '1:745486986028:web:ac10f95bc8629695431a89',
    messagingSenderId: '745486986028',
    projectId: 'macrofit-d0635',
    authDomain: 'macrofit-d0635.firebaseapp.com',
    storageBucket: 'macrofit-d0635.firebasestorage.app',
    measurementId: 'G-M5WQYQX5S1',
  );

}